export enum CardAction {
  PURCHASE = "PURCHASE",
  RESERVE = "RESERVE",
}

export enum TurnAction {
  PURCHASE_DEVELOPMENT_CARD = "PURCHASE_DEVELOPMENT_CARD",
  RESERVE_DEVELOPMENT_CARD = "RESERVE_DEVELOPMENT_CARD",
  BRING_TOKEN = "BRING_TOKEN",
  NO_ACTION = "NO_ACTION",
}